### ISSUE TITLE
Please add a license to this repo. Thank you!

### ISSUE THREAD

**Issue by bodorjzsolt** [themotleyfool/tagish-jaas#1]

**Comment by chriseldredge** [comment]
This code originated from http://free.tagish.net/jaas/index.jsp which is no longer online, but snapshots can be found on the Internet Archive, at https://web.archive.org/web/20050206180558/http://free.tagish.net/jaas/index.jsp.

That page shows the code licensed under LGPL, which can be confirmed in the doc/index.html file in this repository.

**Comment by chriseldredge** [comment]
Added LGPL 2.1 to project per original source code distribution.
